FROM node:18-alpine as build
ARG PROJECT_FOLDER
WORKDIR /app
COPY ${PROJECT_FOLDER}/package*.json ./
RUN npm install
COPY ${PROJECT_FOLDER}/public ./public
COPY ${PROJECT_FOLDER}/src ./src
RUN npm run build

FROM nginx:1.21-alpine
ARG BUILD_FOLDER
ARG EXPORT_PORT
COPY --from=build /app/build /usr/share/nginx/html
COPY ${BUILD_FOLDER}/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE ${EXPORT_PORT}
CMD ["nginx", "-g", "daemon off;"]
